export type QuestionType = "integer" | "decimal" | "decimal_with_unit" | "single_select" | "multi_select" | "likert" | "integer_scale" | "free_text";

export interface AssessmentOption { id: string; label: string; points?: number; isNa?: boolean; }
export interface CanonicalQuestion { id: string; text: string; type: QuestionType; required: boolean; allowNa: boolean; scoringEligible: boolean; domain?: string; reverseScored?: boolean; helpText?: string; options?: AssessmentOption[]; min?: number; max?: number; }
export interface AssessmentModule { id: string; order: number; title: string; purpose: string; questions: CanonicalQuestion[]; }

const freq: AssessmentOption[] = [
  { id: "NVR", label: "Never", points: 0 }, { id: "RLY", label: "Rarely", points: 1 },
  { id: "SMT", label: "Sometimes", points: 2 }, { id: "OFT", label: "Often", points: 3 },
  { id: "ALW", label: "Almost always", points: 4 }, { id: "NA", label: "Not applicable", isNa: true },
];
const yesNo = [{ id: "NO", label: "No", points: 0 }, { id: "YES", label: "Yes", points: 4 }, { id: "UNSURE", label: "Not sure" }, { id: "NA", label: "Not applicable", isNa: true }];
const select = (labels: string[]): AssessmentOption[] => labels.map((label, index) => ({ id: `OPT_${index + 1}`, label }));
const q = (id: number, text: string, type: QuestionType = "likert", options?: AssessmentOption[], extra: Partial<CanonicalQuestion> = {}): CanonicalQuestion => ({ id: `Q${id}`, text, type, required: true, allowNa: type !== "integer" && type !== "decimal" && type !== "decimal_with_unit", scoringEligible: false, options: type === "likert" ? freq : options, ...extra });
const scored = (question: CanonicalQuestion, domain: string, reverseScored = false): CanonicalQuestion => ({ ...question, domain, scoringEligible: true, reverseScored });

const moduleData: Array<[string, string, string, number, number]> = [
  ["M01", "Body Foundations", "Profile and physical measurements", 1, 8],
  ["M02", "Weight & Metabolic History", "Weight trajectory and metabolic context", 9, 15],
  ["M03", "Sleep Recovery Index", "Sleep duration, continuity and restoration", 16, 22],
  ["M04", "Hunger & Satiety Signals", "Hunger, fullness, cravings and meal response", 23, 30],
  ["M05", "Stress Load & Inflammation Signals", "Stress activation and self-reported symptom burden", 31, 40],
  ["M06", "Circadian Health", "Light, screen, meal and sleep timing", 41, 45],
  ["M07", "Physical Activity Mapping", "Frequency, duration and activity pattern", 46, 48],
  ["M08", "Biological Safety Signals", "Perceived resistance, appetite control and energy", 49, 51],
  ["M09", "Root Cause Discovery", "Participant-perceived drivers and caffeine context", 52, 55],
  ["M10", "Hormonal & Reproductive Context", "Optional hormonal and reproductive context", 56, 60],
  ["M11", "Lifestyle & Environment", "Tobacco, alcohol, eating environment and support", 61, 66],
  ["M12", "Goals & Readiness", "Goals, priorities and readiness for change", 67, 71],
  ["M13", "Confidence & Additional Context", "Response confidence and optional participant context", 72, 73],
];

const questions: CanonicalQuestion[] = [
  q(1, "What is your age?", "integer", undefined, { allowNa: false, min: 16, max: 110, helpText: "Enter your age in completed years." }),
  q(2, "What sex were you assigned at birth?", "single_select", select(["Female", "Male", "Intersex", "Prefer not to say"]), { allowNa: false, helpText: "Used for context only; it does not change scores." }),
  q(3, "What is your height?", "decimal", undefined, { allowNa: false, min: 100, max: 250, helpText: "Enter height in centimetres." }),
  q(4, "What is your current weight?", "decimal", undefined, { allowNa: false, min: 25, max: 350, helpText: "Enter weight in kilograms." }),
  q(5, "What is your target weight, if you have one?", "decimal", undefined, { required: false, allowNa: true, min: 25, max: 350, helpText: "Optional; this does not affect scoring." }),
  q(6, "What is your waist circumference?", "decimal_with_unit", [{ id: "CM", label: "Centimetres" }, { id: "IN", label: "Inches" }], { allowNa: false, min: 40, max: 200, helpText: "Measure around the midpoint between the lowest rib and top of the hip bone." }),
  q(7, "How long have you been near your current weight?", "single_select", select(["Less than 6 months", "6-12 months", "1-3 years", "3-5 years", "More than 5 years", "Not applicable"])),
  q(8, "How would you describe your weight pattern over the last five years?", "single_select", select(["Mostly stable", "Gradual increase", "Repeated loss and regain", "Recent marked change", "Other or unsure", "Not applicable"])),
  scored(q(9, "How did the weight change that concerns you begin?", "single_select", select(["No concerning change or mostly stable", "After an identifiable life period or event", "Gradually with no single clear reason", "In repeated cycles of loss and regain", "Rapidly or unexpectedly", "Not applicable"])), "MR"),
  scored(q(10, "How often have well-planned diet or activity efforts produced less change than you expected?"), "MR"),
  scored(q(11, "After an intentional weight loss, how often has some or all of the weight returned?"), "MR"),
  scored(q(12, "How many meaningful cycles of weight loss and regain have you experienced?", "single_select", select(["None", "One", "Two", "Three or four", "Five or more", "Not applicable"])), "MR"),
  q(13, "Have you been told by a clinician that you have any of the following?", "multi_select", select(["None of these", "Type 2 diabetes", "Prediabetes", "High blood pressure", "High cholesterol or triglycerides", "Thyroid condition", "Polycystic ovary syndrome", "Sleep apnoea", "Other", "Prefer not to say", "Not applicable"])),
  q(14, "Are you currently using medicines that may relate to metabolism, appetite, weight or hormones?", "multi_select", select(["No", "Glucose-lowering medicine", "Weight-management medicine", "Long-term corticosteroid", "Hormonal medicine", "Other relevant medicine", "Not sure", "Prefer not to say", "Not applicable"])),
  q(15, "Does a first-degree relative have a history of type 2 diabetes or substantial weight-related metabolic difficulty?", "single_select", yesNo),
  scored(q(16, "How many hours of sleep do you typically get in a 24-hour period?", "single_select", select(["Less than 5 hours", "5 to less than 6 hours", "6 to less than 7 hours", "7 to 9 hours", "More than 9 hours", "Not applicable"])), "SR"),
  ...[17, 18, 19, 20, 21, 22].map((id) => scored(q(id, ({17:"How often do you feel tired even after what seemed like enough time in bed?",18:"How often do you wake during the night and struggle to return to sleep?",19:"How often is your bedtime after midnight?",20:"How often do you remain awake until 2:00 AM or later because you cannot settle to sleep?",21:"How often do you snore loudly, wake gasping, or receive feedback that your breathing pauses during sleep?",22:"How often do you experience a marked afternoon energy crash?"} as Record<number,string>)[id]), "SR")),
  ...[23,24,25,26,27,28,29,30].map((id) => scored(q(id, ({23:"How often do you feel physically hungry within two hours after a full meal?",24:"How often do you experience food cravings when you are not physically hungry?",25:"How often do you eat enough but still fail to feel comfortably full?",26:"How often do you feel comfortably full after a normal meal?",27:"How often are you hungry again three to four hours after a protein-rich meal?",28:"How often does a protein-rich meal keep you satisfied for four hours or longer?",29:"How often do you feel sleepy, foggy or low in energy after a main meal?",30:"When you start eating sweets or snack foods, how often is it difficult to stop at the amount you intended?"} as Record<number,string>)[id]), "HS", id === 26 || id === 28)),
  ...[31,32,33,34].map((id) => scored(q(id, ({31:"How often do you feel persistent physical tension or stress?",32:"How often does stress increase your desire to eat?",33:"How often does your mind race when you are trying to sleep?",34:"How often are cravings noticeably stronger in the evening?"} as Record<number,string>)[id]), "SL")),
  ...[35,36,37,38,39,40].map((id) => scored(q(id, ({35:"How often do you experience bloating, gas or digestive discomfort?",36:"How often do you experience brain fog after meals?",37:"How often do you experience unexplained joint pain or stiffness?",38:"How often does fat around your waist seem resistant to your usual efforts?",39:"How often do you experience unusual thirst or a dry mouth?",40:"How often have reducing calories and increasing activity produced little sustained change?"} as Record<number,string>)[id]), "IB")),
  ...[41,42,43,44,45].map((id) => scored(q(id, ({41:"How often do you spend the first hour after waking indoors without natural daylight exposure?",42:"How often do you use a phone, tablet or computer during the final hour before sleep?",43:"How often do you eat within three hours of bedtime?",44:"How often does your sleep schedule vary by more than two hours across the week?",45:"How often do you feel more alert late at night than during the morning?"} as Record<number,string>)[id]), "CH")),
  scored(q(46, "On how many days per week do you complete intentional physical activity?", "single_select", select(["0 days", "1-2 days", "3-4 days", "5-7 days", "Not applicable"])), "MR"),
  scored(q(47, "On active days, what is the usual duration of your intentional activity?", "single_select", select(["Less than 10 minutes", "10-29 minutes", "30-59 minutes", "60 minutes or more", "Not applicable"])), "MR"),
  scored(q(48, "Which option best describes your usual physical activity pattern?", "single_select", select(["No intentional activity", "Light movement or daily activities", "Mostly aerobic activity", "Mostly resistance training", "A mix of aerobic and resistance activity", "Not applicable"])), "MR"),
  ...[49,50,51].map((id) => scored(q(id, ({49:"How often does your body seem to resist weight loss despite consistent effort?",50:"How often does hunger feel stronger than your ability to regulate it?",51:"How often are your energy levels lower than you believe they should be?"} as Record<number,string>)[id]), "BS")),
  q(52, "When stressed, what responses are most typical for you?", "multi_select", select(["Eat or seek snack foods", "Withdraw or avoid people", "Walk or move", "Use breathing or relaxation", "Talk with someone", "Work more or stay busy", "Other", "Not sure", "Not applicable"])),
  q(53, "What do you believe most often contributes to your hunger or cravings?", "multi_select", select(["Low protein, fibre or meal size", "Stress or emotion", "Poor sleep", "Habit or availability", "Medicine-related", "Not sure", "Other", "Not applicable"])),
  q(54, "What do you believe most often contributes to low energy?", "multi_select", select(["Sleep or recovery", "Stress", "Low activity", "Meal pattern", "Medicine-related", "A known health concern", "Not sure", "Other", "Not applicable"])),
  q(55, "How many caffeinated drinks do you usually consume per day?", "single_select", select(["0 drinks", "1 drink", "2 drinks", "3 drinks", "4 or more drinks", "Not applicable"])),
  q(56, "Which hormonal or reproductive stage best describes your current situation?", "single_select", select(["Not applicable to me", "Regular menstrual cycles", "Irregular menstrual cycles", "Perimenopause", "Postmenopause", "Pregnant or within one year after birth", "Male hormonal context", "Other or unsure", "Prefer not to say"])),
  q(57, "How often have hormonal or reproductive changes affected sleep, appetite, energy or weight?"), q(58, "Are you currently using hormonal medication, contraception or hormone therapy?", "single_select", yesNo), q(59, "How often do appetite or weight patterns change alongside hormonal or reproductive symptoms?"), q(60, "Have you been told by a clinician that you have a thyroid, reproductive or other hormonal concern?", "single_select", yesNo),
  q(61, "How often do you smoke, vape or use nicotine?", "single_select", select(["Never", "Former use", "Occasional", "Daily", "Prefer not to say", "Not applicable"])), q(62, "How often do you consume alcohol?", "single_select", select(["Never", "Monthly or less", "1-2 days per week", "3 or more days per week", "Prefer not to say", "Not applicable"])), q(63, "Which description best matches your usual eating pattern?", "single_select", select(["Regular meals with varied foods", "Irregular meals", "Frequent grazing or snacking", "Alternating restriction and overeating", "A specific dietary pattern", "Other", "Not applicable"])), q(64, "How often are your meals reasonably consistent in timing from day to day?"), q(65, "How supportive is your home food environment of the choices you want to make?", "single_select", select(["Not at all supportive", "A little supportive", "Mixed or inconsistent", "Supportive", "Very supportive", "Not applicable"])), q(66, "How much practical or emotional support do you have for making health-related changes?", "single_select", select(["Not at all supportive", "A little supportive", "Mixed or inconsistent", "Supportive", "Very supportive", "Not applicable"])),
  q(67, "What is your primary goal for completing this assessment?", "single_select", select(["Understand weight resistance", "Improve energy", "Improve sleep and recovery", "Understand hunger or cravings", "Understand stress patterns", "Support long-term prevention and healthy ageing", "Other"]), { allowNa: false }), q(68, "Which area would you most like to understand first?", "single_select", select(["Metabolic resistance", "Hunger and satiety", "Sleep recovery", "Circadian health", "Stress load", "Inflammation burden", "Biological safety", "Not sure"]), { allowNa: false }), q(69, "How ready do you feel to try one small, realistic change during the next two weeks?", "integer_scale", undefined, { allowNa: false, min: 0, max: 10 }), q(70, "How confident are you that you can maintain one small change for two weeks?", "integer_scale", undefined, { allowNa: false, min: 0, max: 10 }), q(71, "What pace of change feels most realistic for you?", "single_select", select(["One small step at a time", "Two or three coordinated changes", "A structured 90-day plan", "I want to understand first"]), { allowNa: false }), q(72, "How confident are you that your answers reflect your usual experience during the last four weeks?", "single_select", select(["Not very confident", "Moderately confident", "Confident", "Very confident"]), { allowNa: false }), q(73, "Is there anything else you would like the report to acknowledge?", "free_text", undefined, { required: false, allowNa: false, max: 1000, helpText: "Optional. Do not enter urgent or emergency information here." }),
];

export const assessmentModules: AssessmentModule[] = moduleData.map(([id, title, purpose, start, end], index) => ({ id, order: index + 1, title, purpose, questions: questions.filter((item) => { const number = Number(item.id.slice(1)); return number >= start && number <= end; }) }));
export const allQuestions = questions;
export const questionCount = 73;
export const moduleCount = 13;
