import type { Metadata } from "next";
import LegalPage from "@/components/layout/LegalPage";

export const metadata: Metadata = { title: "Cookie Notice" };

const cookieSections = [
  { category: "Strictly necessary", treatment: "Authentication, secure sessions, CSRF protection, load balancing and preference storage", control: "Always active where necessary for service delivery and security." },
  { category: "Public-site analytics", treatment: "Aggregate page and conversion measurement on public pages only", control: "Disabled until required consent; withdraw through cookie controls." },
  { category: "Advertising", treatment: "No behavioural advertising or retargeting in Phase 1", control: "Not used." },
  { category: "Session replay", treatment: "Prohibited on assessment, report, authentication and admin routes", control: "Not used on protected routes." },
  { category: "Health data", treatment: "Never placed in analytics, advertising or replay payloads", control: "Mandatory technical control." },
];

export default function CookiesPage() {
  return <LegalPage eyebrow="ROOTS / LEGAL" title="Cookie Notice" intro="We use essential technologies to keep ROOTS-AI™ secure. With your permission, we may use limited analytics on public pages. We do not use advertising pixels or session replay on assessment, report, sign-in or admin pages." sections={[{ title: "Your choices", text: "Optional public-site analytics are used only where permitted and consented. Use the controls in the notice to accept, reject or manage the optional categories, and withdraw at any time from the Cookie Notice." }]} relatedLinks={[{ label: "Privacy Notice", href: "/privacy" }]}>
    <div className="legal-table-wrap"><h2>How each category is treated in Phase 1</h2><table className="legal-treatment-table"><thead><tr><th>Category</th><th>Phase 1 treatment</th><th>Consent/control</th></tr></thead><tbody>{cookieSections.map((item) => <tr key={item.category}><th scope="row">{item.category}</th><td>{item.treatment}</td><td>{item.control}</td></tr>)}</tbody></table></div>
    <div className="legal-table-wrap"><h2>Phase 1 implementation inventory</h2><p>This inventory records technologies used by the current application. Provider and duration values are implementation observations unless explicitly marked as an open controlled-source verification item.</p><table className="legal-inventory-table"><thead><tr><th>Category</th><th>Technology</th><th>Purpose</th><th>Provider</th><th>Duration</th></tr></thead><tbody><tr><th scope="row">Session security</th><td><code>roots_session_id</code> HTTP-only cookie</td><td>Secure assessment session, save/resume and route authorization.</td><td>ROOTS-AI application server; hosting provider remains deployment-dependent and must be confirmed in the processor register.</td><td>Up to 60 minutes (<code>SESSION_TTL_SECONDS</code>); browser expiry or server expiry may end it earlier.</td></tr><tr><th scope="row">Browser storage</th><td><code>localStorage</code> / <code>sessionStorage</code></td><td>No application preference or analytics record is currently implemented in this release candidate.</td><td>Not applicable — no browser-storage provider is used in this release candidate.</td><td>Not applicable — no browser-storage record is implemented; the OPS-03 retention/evidence rule remains open.</td></tr></tbody></table></div>
    <div className="legal-open-item"><h2>OPS-03 — open verification</h2><p>The current release does not introduce a persistent visitor identifier or server-side visitor tracking to record an anonymous analytics preference. Before browser-only storage is approved, the required record must map consent version, categories, timestamp, region/configuration, withdrawal, changes to consent, and the consequence of cleared browser storage. The current controlled baseline does not specify the complete retention/evidence rule for that record; that gap remains open and no compliance claim is made.</p></div>
    <div className="legal-cookie-actions"><h2>Optional analytics controls</h2><p>Cookie controls are not enabled in this release candidate. Do not interpret the inventory above as consent to analytics processing.</p><div><button type="button" disabled>Accept optional analytics</button><button type="button" disabled>Reject optional analytics</button><button type="button" disabled>Manage choices</button></div></div>
  </LegalPage>;
}
